### ISSUE TITLE
java.lang.NoClassDefFoundError for SupportedEllipticCurvesExtension in google-cloud-datastore

### ISSUE THREAD

**Issue by a-pavlov** [googleapis/google-cloud-java#7027]
Hi,
I use Google Cloud Datastore with java client. 
It works fine in web application with tomcat-8.5.30-jdk8-alpine but doesn't work with tomcat-9.0.27-jdk8-openjdk-slim with NoClassDefFoundError report. 
Here is the similar problem https://stackoverflow.com/questions/49112316/java-lang-noclassdeffounderror-sun-security-ssl-supportedellipticcurvesextensio. 
Client version is the latest.

Stack trace:
`java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension
	at sun.security.ssl.ClientHandshaker.getKickstartMessage(ClientHandshaker.java:1438)
	at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1072)
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1479)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1346)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:108)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:79)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:996)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:429)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:157)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:145)
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:91)
	at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc$1.initialize(HttpDatastoreRpc.java:81)
	at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:91)
	at com.google.datastore.v1.client.Datastore.beginTransaction(Datastore.java:79)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.beginTransaction(HttpDatastoreRpc.java:143)
	at com.google.cloud.datastore.DatastoreImpl$5.call(DatastoreImpl.java:520)
	at com.google.cloud.datastore.DatastoreImpl$5.call(DatastoreImpl.java:516)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.datastore.DatastoreImpl.beginTransaction(DatastoreImpl.java:515)
	at com.google.cloud.datastore.DatastoreImpl.requestTransactionId(DatastoreImpl.java:509)
	at com.google.cloud.datastore.TransactionImpl.<init>(TransactionImpl.java:67)
	at com.google.cloud.datastore.TransactionImpl.<init>(TransactionImpl.java:54)
`

Since we are planning migrate to tomcat 9 I need to make application compatible with it. Please suggest ways how I can fix no class found error.
Thank you.

P.S.
Sorry for duplicate of this ticket here https://github.com/googleapis/google-http-java-client/issues/914

**Comment by chanseokoh** [comment]
I think this cannot be an issue in google-cloud-datastore as a library itself: https://github.com/googleapis/google-http-java-client/issues/914#issuecomment-564781630
