### ISSUE TITLE
google-cloud-recaptchaenterprise 3.80.0 fails at runtime with NoClassDefFoundError: com.google.protobuf.RuntimeVersion$RuntimeDomain (works in 3.79.0)

### ISSUE THREAD

**Issue by nbaiocco** [googleapis/google-cloud-java#11936]
Hi team,

After upgrading com.google.cloud:google-cloud-recaptchaenterprise from 3.79.0 to 3.80.0 we get a runtime failure:

java.lang.NoClassDefFoundError: com/google/protobuf/RuntimeVersion$RuntimeDomain
  at com.google.recaptchaenterprise.v1.CreateAssessmentRequest.<clinit>(CreateAssessmentRequest.java:40)
  at com.google.cloud.recaptchaenterprise.v1.stub.GrpcRecaptchaEnterpriseServiceStub.<clinit>(GrpcRecaptchaEnterpriseServiceStub.java:93)
  at com.google.cloud.recaptchaenterprise.v1.RecaptchaEnterpriseServiceClient.create(RecaptchaEnterpriseServiceClient.java:601)
  ...

Caused by: java.lang.ClassNotFoundException: com.google.protobuf.RuntimeVersion$RuntimeDomain

This does not happen with 3.79.0.

Environment
- Runtime: Keycloak 26.5.2 (Quarkus-based)
- At runtime, protobuf-java is provided by the container and is com.google.protobuf:protobuf-java:3.25.5
- Application code only needs to create the client and call CreateAssessment.

Question
- Is protobuf-java 3.25.5 still supported for google-cloud-recaptchaenterprise 3.80.0?
- If not, could you please document/enforce the minimum required protobuf-java version (dependency constraints / BOM alignment), since 3.79.0 worked with 3.25.5 and 3.80.0 now fails?

Thanks!

**Comment by blakeli0** [comment]
Hi @nbaiocco, please take a look at the release notes of libraries-bom [v26.75.0](https://github.com/googleapis/java-cloud-bom/releases/tag/v26.75.0). Protobuf gen code and runtime have been upgraded to `4.33.2` for all google cloud client libraries, including `recaptchaenterprise`. The minimum supported version of protobuf-java is now `4.33.2`.

Please note that protobuf-java 3.x will be [end of support by March 2027](https://protobuf.dev/support/version-support/#java), and [protobuf-java v4.33.0](https://github.com/protocolbuffers/protobuf/releases/tag/v33.0) is fully backward compatible with 3.x gen code. I would suggest to upgrade `protobuf-java` to 4.33.2+ if you manage `protobuf-java` by yourself, or use `libraries-bom` 26.75.0+ which should includes  protobuf-java 4.33.2 already.
